version: "3.9"
services:
  mongo-csgo-checker:
    container_name: mongo-csgo-checker
    image: mongo:latest
    restart: on-failure
    env_file:
      - .env
    ports:
      - "27020:27017"
    networks:
      - steam-csgo-checker-network
    volumes:
      - mongodb:/data/db
  redis-csgo-checker:
    container_name: redis-csgo-checker
    command: redis-server --appendonly yes --replica-read-only no
    image: redis:alpine
    restart: on-failure
    ports:
      - "6380:6379"
    volumes:
      - redis-cache:/data/redis
    networks:
      - steam-csgo-checker-network
  steam-csgo-checker:
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - steam-csgo-checker-network
    volumes:
      - ./logs:/usr/src/app/logs
    env_file:
      - .env
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - mongo-csgo-checker
      - redis-csgo-checker
volumes:
  redis-cache:
    driver: local
  mongodb:
networks:
  steam-csgo-checker-network:
    driver: bridge